### ISSUE TITLE
Sanitize UTF-U

### ISSUE THREAD

**Issue by Chris-628** [patrikcze/meshtatic_py#22]
Já nevím v DB to nevadí, ale do konzole (i nové co umí UTF-8 to píše haluze:
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Filip\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\Filip\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1250.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 136-139: character maps to <undefined>
Call stack:
  File "C:\Users\Filip\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1009, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Filip\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\Filip\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Filip\AppData\Local\Programs\Python\Python312\Lib\site-packages\meshtastic\util.py", line 288, in _run
    o()
  File "C:\Users\Filip\AppData\Local\Programs\Python\Python312\Lib\site-packages\meshtastic\mesh_interface.py", line 1297, in <lambda>
    lambda: pub.sendMessage(topic, packet=asDict, interface=self)
  File "C:\Users\Filip\AppData\Local\Programs\Python\Python312\Lib\site-packages\pubsub\core\publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "C:\Users\Filip\AppData\Local\Programs\Python\Python312\Lib\site-packages\pubsub\core\topicobj.py", line 452, in publish
    self.__sendMessage(msgData, topicObj, msgDataSubset)
  File "C:\Users\Filip\AppData\Local\Programs\Python\Python312\Lib\site-packages\pubsub\core\topicobj.py", line 482, in __sendMessage
    listener(data, self, allData)
  File "C:\Users\Filip\AppData\Local\Programs\Python\Python312\Lib\site-packages\pubsub\core\listener.py", line 237, in __call__
    cb(**kwargs)
  File "D:\Meshtasticinfo\maki\3\get-reply-noemoji.py", line 345, in on_receive
    upsert_node(fromId, from_node_number, from_short_name, from_long_name, from_hw_model, from_last_heard)
  File "D:\Meshtasticinfo\maki\3\get-reply-noemoji.py", line 228, in upsert_node
    logger.info(f"Upserting node: user_id={user_id}, node_number={node_number}, short_name={short_name}, long_name={long_name}, hw_model={hw_model}, last_heard={last_heard}")
Message: 'Upserting node: user_id=!897fd0fd, node_number=2306855165, short_name=cn05, long_name=carson-uzb🗼☀️🔋, hw_model=RAK4631, last_heard=1724245388'
Arguments: ()

**Comment by patrikcze** [comment]
Need to run couple of tests on Windows.
